// This code is auto-generated by the shader processor.

#![allow(dead_code)]

pub mod lights_bin_comp;
pub mod lights_build_lists_comp;
pub mod mesh_adv_textured_frag;
pub mod mesh_adv_textured_vert;
pub mod mesh_adv_untextured_frag;
pub mod mesh_adv_untextured_vert;
pub mod mesh_adv_wireframe_frag;
pub mod mesh_adv_wireframe_vert;
pub mod mesh_culling_comp;
pub mod shadow_atlas_clear_tiles_vert;
pub mod shadow_atlas_depth_vert;
