// This code is auto-generated by the shader processor.

#![allow(dead_code)]

pub mod mesh_basic_textured_frag;
pub mod mesh_basic_textured_vert;
pub mod mesh_basic_untextured_frag;
pub mod mesh_basic_untextured_vert;
pub mod mesh_basic_wireframe_frag;
pub mod mesh_basic_wireframe_vert;
