// This code is auto-generated by the shader processor.

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

#[derive(Copy, Clone, Debug, Default, Serialize, Deserialize)]
#[repr(C)]
pub struct PerFrameUboStd140 {
    pub view_proj: [[f32; 4]; 4],       // +0 (size: 64)
} // 64 bytes

pub type PerFrameUboUniform = PerFrameUboStd140;

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    #[allow(non_snake_case)]
    fn test_struct_PerFrameUboStd140() {
        assert_eq!(std::mem::size_of::<PerFrameUboStd140>(), 64);
        assert_eq!(std::mem::size_of::<[[f32; 4]; 4]>(), 64);
        assert_eq!(std::mem::align_of::<[[f32; 4]; 4]>(), 4);
        assert_eq!(memoffset::offset_of!(PerFrameUboStd140, view_proj), 0);
    }
}
