// This code is auto-generated by the shader processor.

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Debug, Default, Serialize, Deserialize)]
#[repr(C)]
pub struct PerFrameUboStd140 {
    pub view_proj: [[f32; 4]; 4], // +0 (size: 64)
} // 64 bytes

pub type PerFrameUboUniform = PerFrameUboStd140;

pub const PER_FRAME_DATA_DESCRIPTOR_SET_INDEX: usize = 0;
pub const PER_FRAME_DATA_DESCRIPTOR_BINDING_INDEX: usize = 0;

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_struct_per_frame_ubo_std140() {
        assert_eq!(std::mem::size_of::<PerFrameUboStd140>(), 64);
        assert_eq!(std::mem::size_of::<[[f32; 4]; 4]>(), 64);
        assert_eq!(std::mem::align_of::<[[f32; 4]; 4]>(), 4);
        assert_eq!(memoffset::offset_of!(PerFrameUboStd140, view_proj), 0);
    }
}
