// This code is auto-generated by the shader processor.

pub mod bloom_blur_frag;
pub mod bloom_combine_frag;
pub mod bloom_extract_frag;
pub mod compute_test_comp;
pub mod debug_frag;
pub mod debug_vert;
pub mod imgui_frag;
pub mod imgui_vert;
pub mod mesh_frag;
pub mod mesh_shadow_map_vert;
pub mod mesh_vert;
pub mod postprocess_vert;
pub mod skybox_frag;
pub mod skybox_vert;
pub mod sprite_frag;
pub mod sprite_vert;
