// This code is auto-generated by the shader processor.

pub mod bloom_blur_frag;
pub mod bloom_combine_frag;
pub mod bloom_extract_frag;
pub mod compute_test_comp;
pub mod debug_frag;
pub mod debug_vert;
pub mod depth_vert;
pub mod egui_frag;
pub mod egui_vert;
pub mod imgui_frag;
pub mod imgui_vert;
pub mod mesh_textured_frag;
pub mod mesh_textured_vert;
pub mod mesh_untextured_frag;
pub mod mesh_untextured_vert;
pub mod mesh_wireframe_frag;
pub mod mesh_wireframe_vert;
pub mod postprocess_vert;
pub mod skybox_frag;
pub mod skybox_vert;
pub mod sprite_frag;
pub mod sprite_vert;
pub mod text_frag;
pub mod text_vert;
pub mod tile_layer_frag;
pub mod tile_layer_vert;
