// This code is auto-generated by the shader processor.

#[allow(unused_imports)]
use serde::{Deserialize, Serialize};

pub const PER_OBJECT_DATA_DESCRIPTOR_SET_INDEX: usize = 2;
pub const PER_OBJECT_DATA_DESCRIPTOR_BINDING_INDEX: usize = 0;
