// This code is auto-generated by the shader processor.

#[allow(unused_imports)]
use rafx_resources::RafxResult;

#[allow(unused_imports)]
use rafx_resources::{
    DescriptorSetAllocator, DescriptorSetArc, DescriptorSetInitializer, DynDescriptorSet,
    ImageViewResource, ResourceArc,
};
