// This code is auto-generated by the shader processor.

#[allow(unused_imports)]
use rafx::RafxResult;

#[allow(unused_imports)]
use rafx::framework::{
    DescriptorSetAllocator, DescriptorSetArc, DescriptorSetBindings, DescriptorSetInitializer,
    DescriptorSetWriter, DescriptorSetWriterContext, DynDescriptorSet, ImageViewResource,
    ResourceArc,
};

#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct BuildHistogramConfigStd140 {
    pub input_width: u32,             // +0 (size: 4)
    pub input_height: u32,            // +4 (size: 4)
    pub min_log_luma: f32,            // +8 (size: 4)
    pub one_over_log_luma_range: f32, // +12 (size: 4)
} // 16 bytes

impl Default for BuildHistogramConfigStd140 {
    fn default() -> Self {
        BuildHistogramConfigStd140 {
            input_width: <u32>::default(),
            input_height: <u32>::default(),
            min_log_luma: <f32>::default(),
            one_over_log_luma_range: <f32>::default(),
        }
    }
}

pub type BuildHistogramConfigUniform = BuildHistogramConfigStd140;

#[derive(Copy, Clone, Debug)]
#[repr(C)]
pub struct HistogramDataStd430 {
    pub data: [u32; 256], // +0 (size: 1024)
} // 1024 bytes

pub type HistogramDataBuffer = HistogramDataStd430;

pub const CONFIG_DESCRIPTOR_SET_INDEX: usize = 0;
pub const CONFIG_DESCRIPTOR_BINDING_INDEX: usize = 0;
pub const TEX_DESCRIPTOR_SET_INDEX: usize = 0;
pub const TEX_DESCRIPTOR_BINDING_INDEX: usize = 1;
pub const SMP_DESCRIPTOR_SET_INDEX: usize = 0;
pub const SMP_DESCRIPTOR_BINDING_INDEX: usize = 2;
pub const HISTOGRAM_DATA_DESCRIPTOR_SET_INDEX: usize = 0;
pub const HISTOGRAM_DATA_DESCRIPTOR_BINDING_INDEX: usize = 3;

pub struct DescriptorSet0Args<'a> {
    pub config: &'a BuildHistogramConfigUniform,
    pub tex: &'a ResourceArc<ImageViewResource>,
    pub histogram_data: &'a HistogramDataBuffer,
}

impl<'a> DescriptorSetInitializer<'a> for DescriptorSet0Args<'a> {
    type Output = DescriptorSet0;

    fn create_dyn_descriptor_set(
        descriptor_set: DynDescriptorSet,
        args: Self,
    ) -> Self::Output {
        let mut descriptor = DescriptorSet0(descriptor_set);
        descriptor.set_args(args);
        descriptor
    }

    fn create_descriptor_set(
        descriptor_set_allocator: &mut DescriptorSetAllocator,
        descriptor_set: DynDescriptorSet,
        args: Self,
    ) -> RafxResult<DescriptorSetArc> {
        let mut descriptor = Self::create_dyn_descriptor_set(descriptor_set, args);
        descriptor.0.flush(descriptor_set_allocator)?;
        Ok(descriptor.0.descriptor_set().clone())
    }
}

impl<'a> DescriptorSetWriter<'a> for DescriptorSet0Args<'a> {
    fn write_to(
        descriptor_set: &mut DescriptorSetWriterContext,
        args: Self,
    ) {
        descriptor_set.set_buffer_data(CONFIG_DESCRIPTOR_BINDING_INDEX as u32, args.config);
        descriptor_set.set_image(TEX_DESCRIPTOR_BINDING_INDEX as u32, args.tex);
        descriptor_set.set_buffer_data(
            HISTOGRAM_DATA_DESCRIPTOR_BINDING_INDEX as u32,
            args.histogram_data,
        );
    }
}

pub struct DescriptorSet0(pub DynDescriptorSet);

impl DescriptorSet0 {
    pub fn set_args_static(
        descriptor_set: &mut DynDescriptorSet,
        args: DescriptorSet0Args,
    ) {
        descriptor_set.set_buffer_data(CONFIG_DESCRIPTOR_BINDING_INDEX as u32, args.config);
        descriptor_set.set_image(TEX_DESCRIPTOR_BINDING_INDEX as u32, args.tex);
        descriptor_set.set_buffer_data(
            HISTOGRAM_DATA_DESCRIPTOR_BINDING_INDEX as u32,
            args.histogram_data,
        );
    }

    pub fn set_args(
        &mut self,
        args: DescriptorSet0Args,
    ) {
        self.set_config(args.config);
        self.set_tex(args.tex);
        self.set_histogram_data(args.histogram_data);
    }

    pub fn set_config(
        &mut self,
        config: &BuildHistogramConfigUniform,
    ) {
        self.0
            .set_buffer_data(CONFIG_DESCRIPTOR_BINDING_INDEX as u32, config);
    }

    pub fn set_tex(
        &mut self,
        tex: &ResourceArc<ImageViewResource>,
    ) {
        self.0.set_image(TEX_DESCRIPTOR_BINDING_INDEX as u32, tex);
    }

    pub fn set_histogram_data(
        &mut self,
        histogram_data: &HistogramDataBuffer,
    ) {
        self.0.set_buffer_data(
            HISTOGRAM_DATA_DESCRIPTOR_BINDING_INDEX as u32,
            histogram_data,
        );
    }

    pub fn flush(
        &mut self,
        descriptor_set_allocator: &mut DescriptorSetAllocator,
    ) -> RafxResult<()> {
        self.0.flush(descriptor_set_allocator)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_struct_build_histogram_config_std140() {
        assert_eq!(std::mem::size_of::<BuildHistogramConfigStd140>(), 16);
        assert_eq!(std::mem::size_of::<u32>(), 4);
        assert_eq!(std::mem::align_of::<u32>(), 4);
        assert_eq!(
            memoffset::offset_of!(BuildHistogramConfigStd140, input_width),
            0
        );
        assert_eq!(std::mem::size_of::<u32>(), 4);
        assert_eq!(std::mem::align_of::<u32>(), 4);
        assert_eq!(
            memoffset::offset_of!(BuildHistogramConfigStd140, input_height),
            4
        );
        assert_eq!(std::mem::size_of::<f32>(), 4);
        assert_eq!(std::mem::align_of::<f32>(), 4);
        assert_eq!(
            memoffset::offset_of!(BuildHistogramConfigStd140, min_log_luma),
            8
        );
        assert_eq!(std::mem::size_of::<f32>(), 4);
        assert_eq!(std::mem::align_of::<f32>(), 4);
        assert_eq!(
            memoffset::offset_of!(BuildHistogramConfigStd140, one_over_log_luma_range),
            12
        );
    }

    #[test]
    fn test_struct_histogram_data_std430() {
        assert_eq!(std::mem::size_of::<HistogramDataStd430>(), 1024);
        assert_eq!(std::mem::size_of::<[u32; 256]>(), 1024);
        assert_eq!(std::mem::align_of::<[u32; 256]>(), 4);
        assert_eq!(memoffset::offset_of!(HistogramDataStd430, data), 0);
    }
}
