// This code is auto-generated by the shader processor.

#![allow(dead_code)]

pub mod cas;
pub mod debug3d;
pub mod debug_pip;
pub mod depth;
pub mod depth_velocity;
pub mod egui;
pub mod imgui;
pub mod mesh_adv;
pub mod mesh_basic;
pub mod post_adv;
pub mod post_basic;
pub mod post_shared;
pub mod skybox;
pub mod sprite;
pub mod text;
pub mod tile_layer;
