// This code is auto-generated by the shader processor.

#![allow(dead_code)]

pub mod debug3d;
pub mod debug_pip;
pub mod depth;
pub mod egui;
pub mod imgui;
pub mod mesh_adv;
pub mod mesh_basic;
pub mod post_basic;
pub mod skybox;
pub mod sprite;
pub mod text;
pub mod tile_layer;
